# Generated by Django 5.0.3 on 2024-04-09 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=200)),
                ('menu_price', models.IntegerField()),
                ('menu_category', models.CharField(default='None', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Current_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_count', models.IntegerField(default=0)),
                ('order_date', models.DateTimeField(verbose_name='order_date')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_count', models.IntegerField(default=0)),
                ('order_id', models.IntegerField(default=1)),
                ('order_date', models.DateTimeField(verbose_name='order_date')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.menu')),
            ],
        ),
    ]
