# Generated by Django 5.0.3 on 2024-04-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_category',
            field=models.CharField(default='Coffee', max_length=200),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_price',
            field=models.IntegerField(),
        ),
    ]
