# Generated by Django 5.0.3 on 2024-04-09 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='current_order',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='menu_id',
            new_name='menu',
        ),
    ]
