# Generated by Django 5.0.3 on 2024-04-18 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='None', max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='current_order',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.AlterField(
            model_name='current_order',
            name='order_date',
            field=models.DateTimeField(null=True, verbose_name='order_date'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.category'),
        ),
    ]
