# Generated by Django 5.0.3 on 2024-04-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_rename_menu_id_current_order_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_order',
            name='order_date',
            field=models.DateTimeField(null=True, verbose_name='order_date'),
        ),
    ]
