# Generated by Django 5.0.3 on 2024-04-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_menu_menu_category_alter_menu_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_category',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
