# Generated by Django 5.0.3 on 2024-04-05 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_alter_menu_menu_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('order_type', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.customer')),
            ],
        ),
    ]
